package folders

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
)

// Choice is a folder option suitable for display in Telegram.
type Choice struct {
	Token     string
	RootIndex int
	RootName  string
	Path      string
	Label     string
	Depth     int
}

// Discover returns a bounded, deterministic list of selectable folders. By
// default, each configured root is included at depth 0, followed by descendants
// up to maxDepth. When gitReposOnly is enabled, only folders with .git metadata
// are returned while traversal still walks non-repo parent folders.
func (p *Policy) Discover() ([]Choice, error) {
	if p.maxEntries < 1 {
		return nil, fmt.Errorf("maxEntries must be at least 1")
	}
	if p.maxDepth < 0 {
		return nil, fmt.Errorf("maxDepth must be non-negative")
	}

	choices := make([]Choice, 0, min(p.maxEntries, len(p.roots)))
	for _, root := range p.roots {
		if len(choices) >= p.maxEntries {
			break
		}
		rootChoices, err := p.discoverRoot(root, p.maxEntries-len(choices))
		if err != nil {
			return nil, err
		}
		choices = append(choices, rootChoices...)
	}
	return choices, nil
}

// ResolveToken resolves a token generated by Discover/TokenForPath. It performs
// fresh discovery so deleted or newly escaped paths cannot be selected from stale state.
func (p *Policy) ResolveToken(token string) (string, EffectivePolicy, error) {
	choices, err := p.Discover()
	if err != nil {
		return "", EffectivePolicy{}, err
	}
	for _, choice := range choices {
		if choice.Token == token {
			return p.Resolve(choice.Path)
		}
	}
	return "", EffectivePolicy{}, fmt.Errorf("unknown folder token")
}

func (p *Policy) discoverRoot(root Root, remaining int) ([]Choice, error) {
	entries := make([]Choice, 0, remaining)
	if p.shouldInclude(root.Path) {
		entries = append(entries, p.choiceFor(root, root.Path, 0))
	}
	if len(entries) >= remaining || p.maxDepth == 0 {
		return entries, nil
	}

	type queueItem struct {
		path  string
		depth int
	}
	queue := []queueItem{{path: root.Path, depth: 0}}
	visited := map[string]struct{}{root.Path: {}}
	for len(queue) > 0 && len(entries) < remaining {
		current := queue[0]
		queue = queue[1:]
		if current.depth >= p.maxDepth {
			continue
		}

		children, err := safeChildDirs(current.path, root.Path)
		if err != nil {
			return nil, err
		}
		for _, child := range children {
			if _, ok := visited[child]; ok {
				continue
			}
			visited[child] = struct{}{}

			depth := current.depth + 1
			if p.shouldInclude(child) {
				if len(entries) >= remaining {
					break
				}
				entries = append(entries, p.choiceFor(root, child, depth))
			}
			queue = append(queue, queueItem{path: child, depth: depth})
		}
	}
	return entries, nil
}

func (p *Policy) shouldInclude(path string) bool {
	return !p.gitReposOnly || hasGitMetadata(path)
}

func hasGitMetadata(path string) bool {
	info, err := os.Lstat(filepath.Join(path, ".git"))
	if err != nil {
		return false
	}
	return info.IsDir() || info.Mode().IsRegular()
}

func safeChildDirs(parent, root string) ([]string, error) {
	dirEntries, err := os.ReadDir(parent)
	if err != nil {
		return nil, fmt.Errorf("read directory %q: %w", parent, err)
	}
	sort.Slice(dirEntries, func(i, j int) bool { return dirEntries[i].Name() < dirEntries[j].Name() })

	children := make([]string, 0)
	for _, entry := range dirEntries {
		if entry.Name() == ".git" {
			continue
		}
		if !entry.IsDir() && entry.Type()&os.ModeSymlink == 0 {
			continue
		}
		candidate := filepath.Join(parent, entry.Name())
		canonical, err := canonicalDir(candidate)
		if err != nil {
			// Broken links, permission errors, and non-directories are not selectable.
			continue
		}
		if !isWithin(canonical, root) || canonical == parent {
			continue
		}
		children = append(children, canonical)
	}
	return children, nil
}

func (p *Policy) choiceFor(root Root, path string, depth int) Choice {
	label := root.Name
	if path != root.Path {
		if rel, err := filepath.Rel(root.Path, path); err == nil {
			label = filepath.ToSlash(filepath.Join(root.Name, rel))
		} else {
			label = filepath.Base(path)
		}
	}
	return Choice{
		Token:     tokenForCanonicalPath(path),
		RootIndex: root.Index,
		RootName:  root.Name,
		Path:      path,
		Label:     label,
		Depth:     depth,
	}
}
